name: mcedia_mtv_plugin
version: '1.0-SNAPSHOT'
main: top.tobyprime.mcedia_mtv_plugin.Mcedia_mtv_plugin
api-version: '1.21'
folia-supported: true
permissions:
  mtv.admin:
    description: 所有 MTV 管理权限
    default: op
    children:
      mtv.player.create: true
      mtv.player.edit: true
      mtv.player.teleport: true
      mtv.gui: true
      mtv.channel.create: true
      mtv.channel.manage.others: true
      mtv.channel.control.others: true
  mtv.player.create:
    description: 创建 MTV 播放器
    default: op
  mtv.player.edit:
    description: 编辑 MTV 设置（屏幕/扬声器/播放/移动/删除）
    default: true
  mtv.player.teleport:
    description: 传送到 MTV 播放器
    default: op
  mtv.gui:
    description: 打开 MTV 管理 GUI
    default: true
  mtv.channel.create:
    description: 创建公共频道
    default: true
  mtv.channel.manage.others:
    description: 管理别人创建的公共频道
    default: op
  mtv.channel.control.others:
    description: 控制别人创建且未公开控制的公共频道播放
    default: op
