name: McediaMtvPlugin
version: '1.2.2'
main: top.tobyprime.mcedia_mtv_plugin.McediaMtvPlugin
api-version: '${apiLevel}'
folia-supported: true
commands:
  mtv:
    description: 打开遥控器界面
    usage: /mtv
permissions:
  mtv.admin:
    description: 所有 MTV 管理权限
    default: op
    children:
      mtv.player.create: true
      mtv.player.edit: true
      mtv.player.edit.others: true
      mtv.player.teleport: true
      mtv.gui: true
      mtv.channel.create: true
      mtv.channel.manage.others: true
      mtv.channel.control.others: true
      mtv.hud.subscribe: true
      mtv.hud.unsubscribe: true
  mtv.player.edit.others:
    description: 编辑/删除别人创建的私有 MTV 播放器
    default: op
  mtv.player.create:
    description: 创建 MTV 播放器
    default: true
  mtv.player.edit:
    description: 编辑 MTV 设置（屏幕/扬声器/播放/移动/删除）
    default: true
  mtv.player.teleport:
    description: 传送到 MTV 播放器
    default: op
  mtv.gui:
    description: 打开 MTV 管理 GUI
    default: true
  mtv.channel.create:
    description: 创建公共频道
    default: true
  mtv.channel.manage.others:
    description: 管理别人创建的公共频道
    default: op
  mtv.channel.control.others:
    description: 控制别人创建且未公开控制的公共频道播放
    default: op
  mtv.hud.subscribe:
    description: HUD 订阅频道
    default: true
  mtv.hud.unsubscribe:
    description: HUD 取消订阅
    default: true
